Kimtech/urls.py
#Kimtech urls

from django.urls import path
from . import views

app_name = 'kim'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('lenders', views.lenders, name = 'lenders'),
    path('create_account', views.create_account, name = 'create_account'),
    path('kimAdmin', views.admin, name = 'admin'),
]

Lender_Admin/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('login', views.login, name = 'login'),
    path('add_borrower', views.add_borrower, name = 'add_borrower'),
    path('customers', views.customers, name = 'customers'),
    path('loans', views.loans, name = 'loans'),
    path('repayments', views.repayments, name = 'repayments'),
    path('logout', views.logout, name = 'logout'),
    path('aggreements', views.aggreements, name = 'aggreements'),
    path('status', views.status, name = 'status'),
    path('home', views.home, name = 'home'),
    path('statistics', views.statistics, name = 'statistics'),
    path('profile', views.profile, name = 'profile'),
    path('report_error', views.report_error, name = 'report_error'),
    path('subscription', views.subscription, name = 'subscription'),
    path("webhook", views.webhook, name="webhook"),
]

Lenders/urls.py
from django.contrib import admin
from django.urls import path, include
#devt
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('Kimtech.urls', 'kim'), namespace = 'kim')),
    path('', include(('Lender_Admin.urls', 'app'), namespace = 'app')),
    path('admin', admin.site.urls),
]

#dev't...
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,      document_root=settings.MEDIA_ROOT)

urls.py
from django.contrib import admin
from django.urls import path, include
#devt
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('Kimtech.urls', 'kim'), namespace = 'kim')),
    path('', include(('Lender_Admin.urls', 'app'), namespace = 'app')),
    path('admin', admin.site.urls),
]

#dev't...
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,      document_root=settings.MEDIA_ROOT)

templates/aggreements.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Loan Agreement Details</title>
    <link rel="stylesheet" href="./../static/css/agreements.css">
</head>
<body>

    <!-- Header -->
    <header>
        {% if lender.logo.url != None %}
             <img src="{{lender.logo.url}}" alt="Company Logo" class="logo">
        {% else %}
             <img src="/static/images/logo-placeholder.png" alt="Company Logo" class="logo">
        {% endif %}
        <h1>{{lender.co_name}}</h1>
    </header>

    
    <div class="menu-container">
        <span class="menu-button"><a href="{% url 'app:home' %}">Home</a></span>
            <span class="menu-button"><a href="{% url 'app:add_borrower' %}">Add Loan</a></span>
            <span class="menu-button"><a href="{% url 'app:customers' %}">My Customers</a></span>
            <span class="menu-button"><a href="{% url 'app:loans' %}">Available Loans</a></span>
            <span class="menu-button"><a href="{% url 'app:repayments' %}">Repayments</a></span>
            <span class="menu-button"><a href="statistics">Statistics</a></span>
            <span class="menu-button"><a href="{% url 'app:aggreements' %}">Agreements</a></span>
            <span class="menu-button"><a href="{% url 'app:profile' %}">Profile</a></span>
            <span class="menu-button"><a href="{% url 'app:subscription' %}">Subscriptions</a></span>
            <span class="menu-button"><a href="{% url 'app:report_error' %}">Report Error</a></span>
            <span class="menu-button"><a href="https://wa.me/256706749801?text=Hello Kimtech, I wannt you to help me with...">Help</a></span>
            <span class="menu-button"><a href="https://kimtech.pythonanywhere.com">About Kimtech</a></span>
            <span class="menu-button"><a href="{% url 'app:logout' %}">Logout</a></span>
    </div>

 
    <input type="text" id="searchBox" placeholder="Search name...">

    <!-- Loan Details -->
    <h2 class="section-title">Loan & Agreement Information</h2>
    <div class="container">
    {% if info %}
      {% for i in info %}
      <div class="section">
          <strong>{{ i.borrower_id.name }}</strong>
        <div class="card borrower">
            {% if i.borrower_id.photo.url != None %}
        <img src="{{ i.borrower_id.photo.url }}" alt="Thumbnail" onclick="openImage(this)" class="profile-pic" width="100">
        {% else %}
        <img src="/static/images/blankPerson.jpeg" alt="Thumbnail" onclick="openImage(this)" class="profile-pic" width="100">
        {%endif%}
            <h2>{{ i.borrower_id.name }}</h2>
            <p><strong>Loan ID:</strong> {{ i.loan_id.id }}</p>
            <p><strong>Loan Date:</strong>{{ i.loan_id.loan_Date }}</p>
            <p><strong>Loan Expiry:</strong> {{ i.loan_id.last_date }} </p>
        </div>

        <div class="card agreement">
            <strong>{{ i.borrower_id.name }}</strong>
            <h2>Agreement Details</h2>
            <p><strong>Agreement ID:</strong> {{ i.aggr_id.id }}</p>
            {% if i.aggr_id.aggreement.url != None %}
        <img src="{{ i.aggr_id.aggreement.url }}" alt="Thumbnail" onclick="openImage(this)" class="profile-pic" width="100">
        {% else %}
        <img src="/static/images/blankImage.png" alt="Thumbnail" onclick="openImage(this)" class="profile-pic" width="100">
        {% endif %}
        </div>

        <div class="card asset">
            <strong>{{ i.borrower_id.name }}</strong>
            <h2>Asset Information</h2>
            <p><strong>Asset Name:</strong> {{ i.asset_name }}</p>
            <p><strong>Description:</strong> {{ i.description }}</p>
            {% if i.asset_photo.url != None %}
          <img src="{{ i.asset_photo.url }}" alt="Asset" onclick="openImage(this)" width="100">
          {% else %}
          <img src="/static/images/blankImage.png" alt="Asset" onclick="openImage(this)" width="100">
          {%endif%}
        </div>

        <div class="card ownership">
            <strong>{{ i.borrower_id.name }}</strong>
            <h2>Ownership Proof</h2>
            {% if i.proof.url != None %}
          <img src="{{ i.proof.url }}" alt="Proof" onclick="openImage(this)" width="100">
          {% else %}
          <img src="/static/images/blankImage.png" alt="Proof" onclick="openImage(this)" width="100">
          {% endif %}
        </div>
       </div>
        {% endfor %}
        {% else %}
        <p>Borrowers' agreements and collateral information will appear here. <br> Thsnk you for choosing kimtech Ug </p>
        {% endif %}
    </div>
    
    <div id="modal" onclick ="closeImage()">
             <img id="fullImage" src="">
    </div>

    <script src="./../static/js/agreements.js"></script>

</body>
</html>

templates/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link rel="stylesheet" href="./../static/css/dashboard.css">
</head>

<body>

    <div class="container">
        <div class="header">
            {% if lender.logo.url != None %}
            <img src="{{ lender.logo.url }}" alt="Company Logo" class="logo">
            {% else %}
            <img src="/static/images/logo-placeholder.png" alt="Company Logo" class="logo">
            {% endif %}

            <div class="company-info">
                <div class="company-name">{{ lender.co_name }}</div>
                <div class="company-id">ID: {{ lender.id }}</div>
                <div class="subscription-status">
                    {% if lender.subscription %}
                    Subscription: Active
                    {% else %}

                    Subscription: Expired
                    {% endif %}
                </div>
            </div>

            <div class="notification" onclick="clearNotification()">
                🔔 <span id="notif-count">{{count}}</span>
            </div>
        </div>

        <div class="menu-container">
            <div class="menu">
                <button><a href="{% url 'app:home' %}">Home</a></button>
                <button><a href="{% url 'app:add_borrower' %}">Add Loan</a></button>
                <button><a href="{% url 'app:customers' %}">My Customers</a></button>
                <button><a href="{% url 'app:loans' %}">Available Loans</a></button>
                <button><a href="{% url 'app:repayments' %}">Repayments</a></button>
                <button><a href="statistics">Statistics</a></button>
                <button><a href="{% url 'app:aggreements' %}">Agreements</a></button>
                <button><a href="{% url 'app:profile' %}">Profile</a></button>
                <button><a href="{% url 'app:subscription' %}">Subscriptions</a></button>
                <button><a href="{% url 'app:report_error' %}">Report Error</a></button>
                <button><a
                        href="https://wa.me/256706749801?text=Hello Kimtech, I wannt you to help me with...">Help</a></button>
                <button><a href="https://kimtech.pythonanywhere.com">About Kimtech</a></button>
                <button><a href="{% url 'app:logout' %}">Logout</a></button>
            </div>
        </div>

        <div class="content">
            <div class="subscription">
                {% if lender.time_left > 5 %}
                <p>Your subscription expires in <strong style="color: green;">{{ lender.time_left }} day(s)</strong>.</p>
                    
                {% elif lender.time_left < 6  and lender.time_left > -1 %}
                <p>Your subscription expires in <strong style="color:orange;">{{ lender.time_left }} day(s)</strong>.</p>
                {% elif lender.time_left < 0 %}
                <p>Your subscription expired on <strong style="color:red;">{{ lender.expiry }} </strong>.</p>
                    
                {% endif %}
                <button class="extend-btn"><a href="{% url 'app:subscription' %}">Subscriptions</a></button>
            </div>
        </div>


        <div style="display: none;" id="notif">

            <div>
                <div>
                    <h4>Notifications </h4>
                </div>
                {% if notifications %}
                <ul>
                    {% for notif in notifications %}
                    <li>{{ notif }}</li>
                    {% endfor %}
                </ul>
                {% else %}
                No notifications.
                {% endif %}
            </div>

        </div>
    </div>

    <script>
        function clearNotification() {
            let nModel = document.getElementById("notif");
            if (nModel.style.display == 'none') {
                nModel.style.display = 'flex';
            }
            else {
                nModel.style.display = 'none';
            }
        }

    </script>

</body>

</html>

templates/lenders.html
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="/static/images/logo.png">
   <!-- <link rel="stylesheet" href="./../static/css/base1.css">-->
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <title>Create Account</title>

    <style>
        body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-color: white;
}


.container {
    width: 80%;
    margin: 20px auto;
    padding: 20px;
    background: white;
    border-radius: 8px;
    box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
}


.header {
    text-align: center;
    padding: 10px;
    background-color: #007bff;
    color: white;
    border-radius: 8px 8px 0 0;
}


.reg-form{
    width: 50%;
    background-color: white;
    display: block;
    padding: 10%;
    text-align: center;
}

label{
    font-weight: bold;
    margin: 20px;
}

input{
    width: 90%;
    margin: 10px;
    border: 2px solid blue;
    border-radius: 5px;
}

button{
    padding-left: 20px;
    padding-right: 20px;
    border: none;
    background-color: #007bff;
    color: white;
    margin: 10%;
    border-radius: 5px;
    font-weight: bold;
}

button:hover{
    background-color: green;
    font-size: larger;
    cursor: pointer;
}

a{
    text-decoration: none;
}

.toggle{
    color: #007bff;
    font-size: 10px;
    cursor: pointer;
}

    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Create Account</h1>
            <p>Register your company with Kimtech Records</p>
        </div>
    
        <div class="reg-form">
            <form action="{% url 'kim:create_account' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
    
                <label for="profile-photo">Company Logo:</label>
                <input type="file" id="profile-photo" name="logo">
    
                <label for="company-name">Company Name</label>
                <input type="text" id="company-name" name="co_name" required>
    
                <label for="phone-number">Phone Number</label>
                <input type="tel" id="phone-number" name="tel" required>
    
                <label for="email">Email</label>
                <input type="email" id="email" name="email" required>
    
                <label for="location">Location</label>
                <input type="text" id="location" name="location" required>
    
                <label for="username">Username</label>
                {% if ex %}
                <br />
                <span style="color:red; font-size: 10px;"> Username already taken, try another one! </span> <br />
                {% endif %}
    
                <input type="text" id="username" name="uname" required>
    
                <label for="password">Password</label>
                <input type="password" id="inputPw" name="pw" required>
    
                <span onclick="show()" class="toggle">Show Password</span> <br>
    
    
                <button type="submit">Register</button>
            </form>
    
        </div>
    
        <p>Already have an account, <a href="{% url 'app:login' %}">Login here</a> To get started.</p>
    </div>
    
<script>
function show(){
    let view = document.getElementById("inputPw");
    if(view.type == 'password'){
        view.type = "text";
    }else{
        view.type = "password";
    }
}

</script>
</body>


</html>

templates/loans.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Loan Management Dashboard</title>
    <link rel="stylesheet" href="./../static/css/loans.css">
</head>
<body>

    <div class="header">
        {% if lender.logo.url != None %}
             <img src="{{lender.logo.url}}" alt="Company Logo" class="logo">
        {% else %}
             <img src="/static/images/logo-placeholder.png" alt="Company Logo" class="logo">
        {% endif %}
        <h1>{{lender.co_name}}</h1>
    </div>
    
<div class="header">
  <span>Tracked Loans Dashboard</span>
</div>

    <div class="menu-container">
        <span class="menu-button"><a href="{% url 'app:home' %}">Home</a></span>
            <span class="menu-button"><a href="{% url 'app:add_borrower' %}">Add Loan</a></span>
            <span class="menu-button"><a href="{% url 'app:customers' %}">My Customers</a></span>
            <span class="menu-button"><a href="{% url 'app:loans' %}">Available Loans</a></span>
            <span class="menu-button"><a href="{% url 'app:repayments' %}">Repayments</a></span>
            <span class="menu-button"><a href="statistics">Statistics</a></span>
            <span class="menu-button"><a href="{% url 'app:aggreements' %}">Agreements</a></span>
            <span class="menu-button"><a href="{% url 'app:profile' %}">Profile</a></span>
            <span class="menu-button"><a href="{% url 'app:subscription' %}">Subscriptions</a></span>
            <span class="menu-button"><a href="{% url 'app:report_error' %}">Report Error</a></span>
            <span class="menu-button"><a href="https://wa.me/256706749801?text=Hello Kimtech, I wannt you to help me with...">Help</a></span>
            <span class="menu-button"><a href="https://kimtech.pythonanywhere.com">About Kimtech</a></span>
            <span class="menu-button"><a href="{% url 'app:logout' %}">Logout</a></span>
    </div>

    <div class="table-container">
        {% if loans %}
        
        <div class="search-container">
            <input type="text" class="search-box" id="searchInput" onkeyup="searchTable()" placeholder="Search by anything...">
        <div id="suggestions" style="position: absolute; background: white; border: 1px solid #ddd; max-height: 200px; overflow-y: auto;"></div>
        <button class="search-btn" onclick="searchTable()">Search</button>
    </div>
        
        <div class="sort-container">
            <select id="sortDropdown" class="sort-dropdown" onchange="sortTable()">
                <option value="1">Borrower_ID</option>
                <option value="2">Name</option>
                <option value="3">Loan_Date</option>
                <option value="4">Loan_Amount</option>
                <option value="7">Total_Loan Amount</option>
                <option value="8">Loan Duration</option>
                <option value="9">Last_Date</option>
            </select>
            
            <button class="sort-btn" onclick="toggleSortOrder()">Change Order</button>
        </div>
        
        <table id="dataTable">
            <thead>
                <tr>
                    <th>Photo</th>
                												<th>Borrower ID</th>
                    <th>Name</th>
                												<th>Loan Date</th>
                												<th>Loan Amount</th>
                												<th>Interest Rate</th>
                												<th>Processing Fee</th>
                										<th>Total Loan Amount</th>
                									<th>Loan Duration</th>
                			  <th>Last Date</th>
                </tr>
            </thead>
            {% for l in loans %}
            <tbody>
                <tr>
                    <td>
                       <img src="{{l.borrower_id.photo.url}}" alt="Thumbnail" onclick ="openImage(this)" width="100" class="profile-pic">
                  				</td>
               <td>{{l.borrower_id.id}}</td>
                    <td>{{l.borrower_id.name}}</td>
                    <td>{{l.loan_Date}}</td>
                  <td>{{l.loan_amount|floatformat:2}}</td>
                    <td>{{l.interest_rate|floatformat:2}}</td>
                    <td>{{l.processing_fee|floatformat:2}}</td>
                  										<td>{{l.total_amm|floatformat:2}}</td>
                  										<td>{{l.duration}} day(s)</td>
                  			  {% if l.last_date < today %}
                  			  <td style="color:red;">{{l.last_date}}</td>
                  			  {%else%}
                  			  <td style="color:green;">{{l.last_date}}</td>
			          {%endif%}
                </tr>
	         			{%endfor%}
            </tbody>
        </table>
        {%else%}
						       <p>No Loan(s) found!</p>
						     {%endif%}
    </div>
        
        <div id="modal" onclick ="closeImage()">
             <img id="fullImage" src="">
        </div>
        <p>Thank you for choosing Kimtech Uganda!!!</p>
        
        
        
    <script src="./../static/js/loans.js"></script>

</body>
</html>

templates/repayments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Repayment History</title>
    <link rel="stylesheet" href="./../static/css/repayments.css">
</head>
<body>
    <div class="container">
        <div class="header">
            {% if lender.logo.url != None %}
             <img src="{{lender.logo.url}}" alt="Company Logo" class="logo">
        {% else %}
             <img src="/static/images/logo-placeholder.png" alt="Company Logo" class="logo">
        {% endif %}
            <span class="company-name">{{lender.co_name}}</span>
        </div>

        <div class="menu-container">
            <span class="menu-button"><a href="{% url 'app:home' %}">Home</a></span>
            <span class="menu-button"><a href="{% url 'app:add_borrower' %}">Add Loan</a></span>
            <span class="menu-button"><a href="{% url 'app:customers' %}">My Customers</a></span>
            <span class="menu-button"><a href="{% url 'app:loans' %}">Available Loans</a></span>
            <span class="menu-button"><a href="{% url 'app:repayments' %}">Repayments</a></span>
            <span class="menu-button"><a href="statistics">Statistics</a></span>
            <span class="menu-button"><a href="{% url 'app:aggreements' %}">Agreements</a></span>
            <span class="menu-button"><a href="{% url 'app:profile' %}">Profile</a></span>
            <span class="menu-button"><a href="{% url 'app:subscription' %}">Subscriptions</a></span>
            <span class="menu-button"><a href="{% url 'app:report_error' %}">Report Error</a></span>
            <span class="menu-button"><a href="https://wa.me/256706749801?text=Hello Kimtech, I wannt you to help me with...">Help</a></span>
            <span class="menu-button"><a href="https://kimtech.pythonanywhere.com">About Kimtech</a></span>
            <span class="menu-button"><a href="{% url 'app:logout' %}">Logout</a></span>
        </div>

        <h1>Repayment History</h1>

        <button onclick="toggleForm()" class="search-btn">Add Repayment</button><br>
        

        <div class="form-container" id="repaymentForm">
          <form action="{% url 'app:repayments' %}" method="POST">
            {% csrf_token %}
            <button class="close-form" onclick="closeForm()">X</button>
            <input type="text" id="search" placeholder="Search name..." onkeyup="showSuggestions()" class="search">
            <div id="suggestions"></div>
            <select id="nameDropdown" name="id" class="search">
                <option value="">Select Name</option>
                {% for l in loans %}
                <option value="{{l.borrower_id.id}}">ID:{{l.borrower_id.id}} => {{l.borrower_id.name}}
                </option>
                {% endfor %}
            </select>
            <input type="number" id="amount" name="paid" placeholder="Enter amount paid" class="search" required>
            <button onclick="submitRepayment()" type="submit" class="search-btn">Submit Payment</button>
          </form>
        </div>

        {% if repayments %}
        
        <input type="text" id="tableSearch" placeholder="Search in table..." onkeyup="filterTable()" class="search">
        
        
        <div class="controls">
  <label for="sortColumn">Sort by:</label>
  <select id="sortColumn">
    <option value="1">Loan Date</option>
    <option value="2">Borrower ID</option>
    <option value="3">Loan ID</option>
    <option value="4">Borrower Name</option>
    <option value="5">Paid Amount</option>
    <option value="6">Percentage Paid</option>
    <option value="7">Days Left</option>
    <option value="8">Loan Balance</option>
  </select>

  <button id="toggleOrder">Toggle Order (Asc)</button>
</div>


        <div class="table-container">
            <table id="repaymentHistory">
                <thead>
                <tr>
                    <th>Photo</th>
                    <th>Loan Date</th>
                    <th>Borrower ID</th>
                    <th>Loan ID</th>
                    <th>Borrower Name</th>
                    <th>Paid Amount</th>
                    <th>Percentage Paid</th>
                    <th>Days Left</th>
                    <th>Loan Balance</th>
                </tr>
                    
                </thead>
                <tbody>
                    {% for r in repayments %}
                <tr>
                    <td>
                        <img src="{{r.borrower_id.photo.url}}" alt="Thumbnail" onclick ="openImage(this)" width="100" class="profile-pic">
                    </td>
                    
                    <td>{{r.loan_id.loan_Date}}</td>
                    <td>{{r.borrower_id.id}}</td>
                    <td>{{r.loan_id.id}}</td>
                    <td>{{r.borrower_id.name}}</td>
                    <td>{{r.paid|floatformat:2}}</td>
                    <td>{{r.percentage_paid|floatformat:2}} %</td>
                    
                    {% if r.time_left < 0 %}
                    <td style="color: red">Expired on {{r.loan_id.last_date}} </td>
                    {% elif r.time_left == 0 %}
                    <td style="color: black; background-color: orange;">Expires today </td>
                    {% else %}
                    <td>{{r.time_left}} day(s)</td>
                    
                    {% endif %}
                    </td>
                    <td>{{r.bal|floatformat:2}}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            
            {% else %}
              <p>Loan Repayment History will appear here. <br> Thank you! </p>
            {% endif %}
            
        </div>
    </div>
    
    <div id="modal" onclick ="closeImage()">
             <img id="fullImage" src="">
        </div>
        <p>Thank you for choosing Kimtech Uganda!!!</p>

    <script src="./../static/js/repayments.js"></script>
</body>
</html>

templates/statistics.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Money Lenders Statistics</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="./../static/css/statistics.css">
</head>

<body>

    <div class="container">
        <div class="header">

            {% if logo.url != None %}
            <img src="{{ logo.url}}" alt="Company Logo" class="logo">

            {% else %}

            <img src="/static/images/logo-placeholder.png" alt="Company Logo" class="logo">

            {% endif %}

            <div class="company-info">
                <div class="company-name">{{name}}</div>
            </div>
        </div>

        <div class="menu-container">
            <div class="menu">
                <button> <a href="{% url 'app:home' %}">Home</a></button>
                <button> <a href="{% url 'app:add_borrower' %}">Add Loan</a></button>
                <button> <a href="{% url 'app:customers' %}">My Customers</a></button>
                <button> <a href="{% url 'app:loans' %}">Available Loans</a></button>
                <button> <a href="{% url 'app:repayments' %}">Repayments</a></button>
                <button> <a href="statistics">Statistics</a></button>
                <button> <a href="{% url 'app:aggreements' %}">Agreements</a></button>
                <button> <a href="{% url 'app:profile' %}">Profile</a> </button>

                <button> <a href="{% url 'app:subscription' %}">Subscriptions</a></button>
                <button> <a href="{% url 'app:report_error' %}">Report Error</a></button>

                <button> <a
                        href="https://wa.me/256706749801?text=Hello Kimtech, I wannt you to help me with...">Help</a></button>
                <button> <a href="https://kimtech.pythonanywhere.com">About Kimtech</a></button>
                <button> <a href="{% url 'app:logout' %}">Logout</a></button>
            </div>
        </div>

        <div>
            <form action="{% url 'app:statistics' %}" method="POST">
                {% csrf_token %}
                <select id="period" name="period" class="search">
                    <option value="1">This month</option>
                    <option value="2">Last Month</option>
                    <option value="3">All</option>
                </select>
                <button type="submit">View</button>
            </form>
        </div>

        <div id="view">
            <h3>{{time}}</h3>
        </div>


        <div class="stats">
            <div class="card">
                <h3>Total No. of Loans Issued</h3>
                <p>{{total_loans}}</p>
            </div>
            <div class="card">
                <h3>Total Amount Disbursed</h3>
                <p>{{total_amm|floatformat:2}}/=</p>
            </div>
            <div class="card">
                <h3>Total Partialy Paid Amount</h3>
                <p>{{part_paid|floatformat:2}}/= ({{ptPaid_rate|floatformat:2}}%)</p>
            </div>
            <div class="card">
                <h3>Successful Repayments</h3>
                <p>Loans :{{success_loans}} ({{rate|floatformat:2}}%) </p>
                <p>Ammount : {{success_pay|floatformat:2}}/= </p>
            </div>
            <div class="card">
                <h3>Unpaid Loan Balance</h3>
                <p style="color: gray;">(With Late Payment Fees Inclusive if exist)</p>
                <p>{{loan_balance|floatformat:2}} /= ({{bal_rate|floatformat:2}}%)</p>
            </div>
            <div class="card">
                <h3>Expected Interest</h3>
                <p style="color: gray;">(With Late Payment Fees Inclusive if exist)</p>
                <p>{{exp_interest|floatformat:2}} /=</p>
            </div>
            <div class="card">
                <h3>Collected Interest</h3>
                <p>{{collected_intr|floatformat:2}}/= ({{intr_rate|floatformat:2}}%)</p>
            </div>
            <div class="card">
                <h3>Late Fees Expected</h3>
                <p>{{penalty|floatformat:2}} /=</p>
            </div>
        </div>



    </div>
    </div>

</body>

</html>